server:
  port: 8760

spring:
  application:
    name: quark-gateway-controller
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/